
# coding: utf-8

# In[236]:

import pandas_datareader.data as web
import pandas as pd
import datetime
import csv
from pandas_datareader._utils import RemoteDataError


# In[246]:

filename = "Ticker_MF.csv"
tickers = []
i = 0
ticker_frame = pd.read_csv(filename)


# In[247]:

ticker_frame.head()


# In[248]:

ticker_frame.fillna(0, inplace=True)


# In[249]:

new_ticker_frame = ticker_frame[ticker_frame.TICKER_SYMBOL_IDENTIFIER != 0]


# In[ ]:




# In[ ]:




# In[250]:

all_tickers = new_ticker_frame["TICKER_SYMBOL_IDENTIFIER"]
for ticker in all_tickers:
    if ticker[0] == 'F':
        tickers.append(str(ticker))
tickers[0]
len(tickers)


# In[251]:

d = {}
data_source = 'yahoo'
start = datetime.datetime(2011,1,1)
end = datetime.datetime(2017,1,1)


# In[252]:

df = web.DataReader(tickers[0], data_source, start, end)
tickers[0]


# In[253]:

df


# In[ ]:




# In[254]:

# Making the index a column
#df.reset_index(level=0, inplace=True)
#df.head()


# In[255]:

df.index


# In[256]:

#annual = df.groupby (pd.Grouper(freq="A")).mean()
df.head()


# In[257]:

#annual.head()
annual_beg = df.groupby(pd.Grouper(freq="A")).nth(0)
annual_beg.head()


# In[258]:

quarter_end = df.groupby(pd.Grouper(freq='Q')).nth(-1)
quarter_end.head()


# In[259]:

#YTD Formula
'''Calculating the YTD return on a portfolio is the same as for a single investment.
    Take the current value of all assets in the portfolio and subtract the total amount 
    invested on the preceding Jan. 1. This renders the total YTD return in dollars. 
    Dividing this figure by the original value and multiplying by 100 converts it into a
    percentage that reflects the return generated by each dollar originally invested.
'''
# ( Current Price ( end of quarter) - original at beg of year)/(orig at beg of year) * 100
q = quarter_end.copy()
q.reset_index(level=0, inplace=True)
a = annual_beg.copy()
a.reset_index(level=0, inplace=True)
q['Year'] = pd.to_datetime(q.Date).dt.year
a['Year'] = pd.to_datetime(a.Date).dt.year
merged = pd.merge(q,a,left_on ="Year",right_on = "Year", how= 'left')
merged['Qtr'] = pd.PeriodIndex(pd.to_datetime(merged.Date_x), freq='Q')
merged["YTD"] = ((merged["Close_x"]-merged["Close_y"])/(merged["Close_y"])) *100
merged
# q.head



# In[ ]:




# In[ ]:



